//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuggesterTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuggesterTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed: 0,fromUser,sent,text
        ///0,misha,2022-05-05T01:16:12.865Z,first0
        ///1,misha,2022-05-05T01:17:12.865Z,first1
        ///2,misha,2022-05-05T01:18:12.865Z,apple linux
        ///3,ivan,2022-05-05T01:19:12.865Z,garlic pumpkin
        ///4,roma,2022-05-05T01:20:12.865Z,shop
        ///5,misha,2022-05-05T01:21:12.865Z,garlic cucumber
        ///6,roma,2022-05-05T01:22:12.865Z,garlic cucumber
        ///7,ivan,2022-05-05T01:23:12.865Z,pumpkin
        ///8,ivan,2022-05-05T01:24:12.865Z,cucumber apple
        ///9,roma,2022-05-05T01:25:12.865Z,garlic
        ///10,ivan,2022-05-05T01:26:12.865Z,last0        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csv_test_suggester_1 {
            get {
                return ResourceManager.GetString("csv_test_suggester_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] test_suggester_1 {
            get {
                object obj = ResourceManager.GetObject("test_suggester_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;job&quot;:[&quot;job&quot;,&quot;work&quot;,&quot;position&quot;,&quot;listing&quot;,&quot;posting&quot;,&quot;freelance&quot;],&quot;dev&quot;:[&quot;developer&quot;,&quot;dev&quot;,&quot;sr&quot;,&quot;jr&quot;,&quot;senior&quot;,&quot;junior&quot;,&quot;middle&quot;],&quot;skill&quot;:[&quot;python&quot;,&quot;django&quot;,&quot;javascript&quot;,&quot;js&quot;,&quot;jquery&quot;,&quot;css&quot;,&quot;ruby&quot;],&quot;area&quot;:[&quot;web&quot;,&quot;webdev&quot;,&quot;gamedev&quot;,&quot;frontend&quot;,&quot;backend&quot;,&quot;fullstack&quot;],&quot;money&quot;:[&quot;pay&quot;,&quot;salary&quot;,&quot;wage&quot;],&quot;fruit&quot;:[&quot;apple&quot;,&quot;orange&quot;],&quot;vegetable&quot;:[&quot;garlic&quot;,&quot;pumpkin&quot;,&quot;cucumber&quot;],&quot;shop&quot;:[&quot;pyaterochka&quot;,&quot;diksi&quot;,&quot;shop&quot;],&quot;brand&quot;:[&quot;asus&quot;,&quot;acer&quot;],&quot;os&quot;:[&quot;windows&quot;,&quot;linux&quot;,&quot;arch&quot;,&quot;ubuntu&quot;]}.
        /// </summary>
        internal static string user_dicts {
            get {
                return ResourceManager.GetString("user_dicts", resourceCulture);
            }
        }
    }
}
